### ISSUE TITLE
Get an error message which is preventing me from uploading data

### ISSUE THREAD

**Issue by joggers7** [ministryofjustice/data-platform-support#138]
### What happened?

Trying to read in  a small dataset from a project which I have uploaded into R
df1 <- read_excel("Replication_data.xlsx")

### Relevant log output

```bash
> df1 <- read_excel("Replication_data.xlsx")
Error in base::nchar(wide_chars$test, type = "width") :                                                                     
  lazy-load database '/home/joggers7/git-training-class/renv/library/R-4.1/x86_64-pc-linux-gnu/cli/R/sysdata.rdb' is corrupt
In addition: Warning messages:
1: In base::nchar(wide_chars$test, type = "width") :
  restarting interrupted promise evaluation
2: In base::nchar(wide_chars$test, type = "width") :
  internal error -3 in R_decompress1
```

**Comment by LouiseABowler** [comment]
Hi @joggers7, this is an error with either your R packages or R code, not the Analytical Platform itself, so I'll only be able to offer limited help here.

A couple of things to try first would be to reinstall the `cli` package as it looks like that is the source of your error, and otherwise try restarting your R session (guide [here](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/rstudio/#rstudio-memory-issues)). If neither of those work, you might be able to get some more guidance from the [#r channel](https://asdslack.slack.com/archives/C1PUCG719).

**Comment by LouiseABowler** [comment]
Hi @joggers7, did you manage to get this working in the end?

**Comment by bagg3rs** [comment]
Closing issue as stale see other comment for further guidance.

> Hi @joggers7, this is an error with either your R packages or R code, not the Analytical Platform itself, so I'll only be able to offer limited help here.
> 
> A couple of things to try first would be to reinstall the `cli` package as it looks like that is the source of your error, and otherwise try restarting your R session (guide [here](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/rstudio/#rstudio-memory-issues)). If neither of those work, you might be able to get some more guidance from the [#r channel](https://asdslack.slack.com/archives/C1PUCG719).
