### ISSUE TITLE
Referencing judge names already in the public domain

### ISSUE THREAD

**Issue by pjooman** [ministryofjustice/data-platform-support#155]
### Which tool do you need help with?

RStudio

### What happened?

Hi there, I am looking for some advice. My team have been writing some code to clean name data to get it ready for matching. For four of the names this was done by referencing the names in the R script which was saved on our internal repo in Github. These are all judge names already in the public domain, the code was something like changing "Johnathan (known as Johnny) Smith" to ("Johnathan Smith"). I think ideally we wouldn't have name on there even if they are in the public domain. I wondered if this is an issue at all, should we be trying to delete the R script permanently say and if so could you please let us know how to do this?

**Comment by ymao2** [comment]
@pjooman,  if the information like the names is public available, from data protection point of view,  even the names are in your R repo, it will be ok, not a issue at all,  but for making your peace of your mind, and also from general good coding practices ( extendability, maintainability etc) point of view,  it is better to store the data somewhere,   so how about to think about to move those names into a data file  and store it somewhere (e.g. s3 bucket),  then change your code to read data from there rather than hardcode those names in the code ,   happy to have a chat if you need more suggestions

**Comment by pjooman** [comment]
Great, thank you so much for your help! We will do as you suggest and let you know if we need any help, thank you. I will close this.
