### ISSUE TITLE
Bucket Access

### ISSUE THREAD

**Issue by r-mccormack** [ministryofjustice/data-platform-support#160]
### Which tool do you need help with?

S3

### What happened?

Please can I be made admin of the alpha-text-embeddings bucket, as the previous admin has left.

Thanks!

**Comment by ymao2** [comment]
@r-mccormack ,  checked the bucket,  found out the bucket has been removed from control panel,  but it still exists on AWS account since Control panel won't delete s3 bucket and it only marked the bucket with a tag of `to-archive` ,  then we will remove the buckets permanently based on this tag from time to time ( in the future it will be run regularly through cronjob)

so I cannot do anything through control panel unless I re-claim the bucket back to control panel,   how about I add the bucket back to the control panel,  assign admin to you?  then up to you to decide whether you want to remove it again in the future?

**Comment by r-mccormack** [comment]
Thanks @ymao2 , that would be ideal. I could see there was something wrong, but that it still seemed to exist, so thanks for clearing that up!

**Comment by r-mccormack** [comment]
Thank you @ymao2. You're an angel!

**Comment by ymao2** [comment]
I assume the bucket works  for you, I close this issue 😄
