### ISSUE TITLE
Users 'Haziach' and 'anna445' unable to log onto the AP

### ISSUE THREAD

**Issue by jessicadaymoj** [ministryofjustice/data-platform-support#161]
### What happened?

When trying to log on to the AP, both users reach the 'There is a problem with your session' screen. They have tried 'reset your session' and then attempted to log in again, only to end up at the same screen.  
Both users work in HMPPS and do not have slack accounts, so raising the issue on their behalf. Their usernames are Haziach and anna445.

I've raised this issue previously for one of the users on 19/06/23. John reset the account and Michael advised the user to try logging in via an incognito window, but unfortunately the problem still persists.

**Comment by ymao2** [comment]
let me check the 2 users

**Comment by ymao2** [comment]
@jessicadaymoj ,  just checked the both users are not within github org `moj-analytical-services`,  the user has to be invited into `moj-analytical-services` in order to be able to access the AP's control panel. 

Based on their record  on control panel,  it seems they logged in before, not sure how they are removed,  could you ask them to follow the guide below to raise the query on operation engineer channel to get them re-invited again
https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html#request-invitation-to-analytical-services-github-organisation

**Comment by jessicadaymoj** [comment]
Thank you @ymao2 - neither user has a slack account. Am I able to make the request on their behalf?

**Comment by ymao2** [comment]
yes! you can

**Comment by jessicadaymoj** [comment]
Thank you!

**Comment by NickWalt01** [comment]
Hello @ymao2 we have automation that removes users we detect are inactive, we run this monthly due to limited GH licenses, this might explain why the users have been removed the GitHub Organisation
