### ISSUE TITLE
AP reading in file from Athena incorrectly

### ISSUE THREAD

**Issue by kings83** [ministryofjustice/data-platform-support#162]
### Which tool do you need help with?

R Studio, AP, Athena

### What happened?

When reading in a file from Athena onto the AP (in R Studio) only 12.5% of the file is read in correctly and the rest is NAs (with the correct row number). It only happens with 1 file and not all the time. The file is completely fine on Athena.

**Comment by ymao2** [comment]
@kings83  will have a look at your namespace

**Comment by ymao2** [comment]
@kings83 I was thinking it may be to do with the memory which only loaded partial of data,  but I just checked your rstudio memory usage,  it was quite ok, not near to the limit at all. There were a few CPU high spike but they were under limit too 

is it possible to link to any particular data column e.g. data type?  may asking the question in [r channel](https://mojdt.slack.com/archives/C1PUCG719)

Also I would suggest to use the following approach to narrow down the searching scope of the root cause:-
- not reading the whole file, instead,  identify a bunch of data which can be viewed on Athena directly  but cannot see them from your code. ---> this way at least can check whether the size of data could be the issue
- not reading all the columns , but pick up simplest column first ---> this way to check whether the issue is linked to specific field.

**Comment by kings83** [comment]
@ymao2 I tried to read the file in smaller chunks today (selecting specific columns only) and had no issues. I then tried to read in the entire thing and it was fine again. This has happened before though - it occasionally reads in completely fine, then the next time I read it in (later that day or next day etc.) the issue comes back and it doesn't read in properly. It's very inconsistent, which is the confusing part.

**Comment by kings83** [comment]
@ymao2 do you have any other suggestions for why this may be happening?

**Comment by ymao2** [comment]
just more information, from running environment you are using through control panel is rstudio , rstudio shouldn't have any link to athena query except memory , but as I mentioned in my comment,  memory usage in your namespace was quite ok,  so only possible causes I can think of are related R package or data itself or code itself,   you maybe try upgrade/downgrade related package? ,  or changing approach to read the data as I mentioned ealier

or try our [r channel ](https://asdslack.slack.com/archives/C1PUCG719) to see whether other people have similar experiences. 

sorry couldn't be more helpful 😊
