### ISSUE TITLE
 I am looking after a FMB for the Segmentation tool and am getting users that I have added saying they can't access it. Brief description of your issue

### ISSUE THREAD

**Issue by susanbaron** [ministryofjustice/data-platform-support#172]
### Which tool do you need help with?

Database Access, User and Account

### What happened?

I have been manning the Segmentation Tool FMB - for a colleague who is on paternity leave.  I normally add users to the approved users list and there are usually no difficulties in them using the link and accessing after that.  For the past 2 months, this has worked fine.   However, in the last 2-3 weeks, I have had 6 users saying that they cannot access in spite of me following the same process to add them onto the user list.  The list also looks different so I wondered if there had been some recent changes/ challenges with the AP that could account for this.  The current issue means many leaders cannot use the tool and there may be more people too. Grateful of any help - my knowledge in these technical issues is fairly limited.                        
  https://segmentation-tool.apps.alpha.mojanalytics.xyz/login

**Comment by ymao2** [comment]
@susanbaron, yes there are some changes,  not sure whether you have been involved in app-migration or not.  We decided to migrate all those known apps over to new cluster,  segmentation-tool is one of them.  I can remember your team has informed  the key developer for this app is on paternity leave,  that is ok,  you can carried the UAT when he comes back. 

Due to it,  there are some changes on the Control panel's UI for managing the customers,   if you want to add the customer to the old app:  https://segmentation-tool.apps.alpha.mojanalytics.xyz/login,  you need click `primary` one, then add them
<img width="1158" alt="Screenshot 2023-07-21 at 10 12 43" src="https://github.com/ministryofjustice/data-platform-support/assets/26111671/48cd5c90-e6f4-4b72-9ee4-cb2acfcaf4fe">

the `dev` and `prod` are for new app which has different URL

By looking at your app, I think you may have added some users into to the `dev` on instead,  could you make sure you choose the right environment ?

**Comment by susanbaron** [comment]
Thankyou – this is really helpful, although of course it would have been even better to have this guidance (use primary not dev – not always intuitive) beforehand as I think I will have frustrated some customers. I have corrected my practice and have emails back from satisfied users who can now gain access – so my problem sorted thankyou.

I have actually just had a meeting with Lu Han from the Data science team ref migration and some other issues regarding the Segmentation tool.  She has asked for a meeting with Julia Lawrence to discuss the migration but our initial thoughts are that the checks needed do not look too complex so we would aim to meet the September deadline.  What does UAT stand for please?

I
Regards

Sue

**Comment by ymao2** [comment]
Glad to hear the problem has been solved!

There are some guide https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html, it is mainly for migrated app.   I agreed `primary` did sound confusing , sorry for this 😊 ,  I will do some update on the above user-guide to make it clearer, but just for clarification,  after migration, all those resources related to old app on alpha cluster including so-called `primary` will be removed entirely from Control panel.

UAT means `User acceptance testing`
