### ISSUE TITLE
RStudio won't load on the AP

### ISSUE THREAD

**Issue by LauraJones01** [ministryofjustice/data-platform-support#178]
### Which tool do you need help with?

RStudio

### What happened?

When I open RStudio on the AP all I see is a loading screen and then a blank screen. Sometimes this does then load but there is a warning message about an unexpected crash. It then will not let me do anything in R. I have tried this in Firefox as well but it was the same. I have also tried restarting R but it has not worked.

**Comment by michaeljcollinsuk** [comment]
Hi @LauraJones01 can I check what version of rstudio are you using? 

When rstudio fails to start it is often because your home directory has got into a bad state and needs to be reset. Have you tried using the "[resetting your home directory](https://controlpanel.services.analytical-platform.service.justice.gov.uk/reset-user-home/)" link from the tools page?

Please close any open rstudio windows/tabs and then give it a try, and then try restarting rstudio again. This process is described in more detail [in the user guidance here](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/rstudio/#clearing-your-rstudio-session). If you have any important files in your home directory, make sure to store them safe (s3 or github) before following this process.

**Comment by michaeljcollinsuk** [comment]
Note for future reference:
User wanted to save code before resetting their home directory, and in this instance was able to get back into the R environment without resetting the home directory. Need to discuss with the team if there is a way to store unsaved code/files before resetting the home directory, in the case that the environment is totally unaccessible.
