### ISSUE TITLE
RStudio stuck on blank screen

### ISSUE THREAD

**Issue by maryboeker** [ministryofjustice/data-platform-support#228]
### Which tool do you need help with?

RStudio

### What happened?

When I select RStudio in the Control Panel it just goes to a blank screen and stays there. 
For context, my RStudio was reset "from the backend" yesterday. After this it was working, although it stayed on the blank screen for a bit before opening up, but now it just doesn't seem to move on from the blank screen at all.

**Comment by michaeljcollinsuk** [comment]
Hi @maryboeker have you been able to access Rstudio at all this morning? Or did the error occur after trying to launch via control panel?

I've checked the metrics and can see that memory usage for your rstudio pod began to shoot up at 8:38 until it reached 12gb, which is the limit, and then died (note timestamps are UTC time so an hour behind):
<img width="452" alt="Screenshot 2023-09-05 at 09 52 42" src="https://github.com/ministryofjustice/data-platform-support/assets/15347726/dbdcc12e-fb96-47a5-9eb4-47def64a00d2">

If you were been using rstudio at the time, was there anything that you ran around this time that could have caused the memory spike? If you had not accessed rstudio it suggests something happened during startup that caused the memory spike.

Since the pod died a new rstudio pod has started, with memory usage much lower and stable. Have you been able to access rstudio again since opening the ticket? Could you please try to access if you have not tried yet.

Also please could you take a screenshot when you encounter the error again (even if just a blank screen) along with the timestamp it occurs. Thanks

**Comment by maryboeker** [comment]
Hello Michael, thank you for your reply. I have not been able to open it up at all today, but around 8.38 may well be when I first tried to open it today. I'm currently still not able to open it. Here is a screenshot:

<img width="1792" alt="Screenshot 2023-09-05 at 10 57 59" src="https://github.com/ministryofjustice/data-platform-support/assets/114941739/12ce6475-019f-40c8-8000-af2b4ea962fc">

**Comment by michaeljcollinsuk** [comment]
> Hello Michael, thank you for your reply. I have not been able to open it up at all today, but around 8.38 may well be when I first tried to open it today. I'm currently still not able to open it. Here is a screenshot:
> 
> <img alt="Screenshot 2023-09-05 at 10 57 59" width="1792" src="https://user-images.githubusercontent.com/114941739/265662627-12ce6475-019f-40c8-8000-af2b4ea962fc.png">

Thanks for the update. I'm going to look into the logs and metrics again now. I am sure you have already tried this, but just to confirm, have you tried closing down the window and using "Restart" button from control panel?

**Comment by maryboeker** [comment]
Yes, I have tried that, as well as selecting different versions of R.

**Comment by michaeljcollinsuk** [comment]
@maryboeker thanks for confirming, could I ask you try one more thing before I take any action my side - could you try to clear your browser cache and/or try to open in a private browser window(or a different browser rather than Safari if you have one installed e.g. chrome). I only ask to try this as according to the metrics/logs the pod is running and stable, so just want to rule out possibilities.

**Comment by maryboeker** [comment]
I just tried opening it in a private browser, but the same thing happened!

**Comment by michaeljcollinsuk** [comment]
Can you try to open with this direct link and let me know what happens please? https://maryboeker-rstudio.tools.analytical-platform.service.justice.gov.uk/

**Comment by maryboeker** [comment]
It asks for TFA first, after I enter that it is the blank screen again.

**Comment by michaeljcollinsuk** [comment]
@maryboeker thanks for trying those for me. I have reset your rstudio session and restarted the instance, can you give it 5/10mins and then try starting up again from Control Panel. Let me know how it goes.

It seems like your RStudio session was struggling to load the R environment based on events from a previous session, e.g. a CPU or memory intensive program/model being run. So if you are able to access now, you may want to see if there is anything in your environment you can clear up.

**Comment by maryboeker** [comment]
Great - I can access it now! There isn't anything displayed as being in my environment, and it says only 125MiB are currently being used. Do I need to check somewhere else?

**Comment by michaeljcollinsuk** [comment]
@maryboeker good to know. So you dont have any particularly large files etc in your environment currently? Are you going to be running any long running/intensive scripts?

I would suggest keeping an eye on the memory usage displayed for you, and I will keep an eye on the monitoring my side too. Another option is that I can try increasing your memory.
