### ISSUE TITLE
Unable to authenticate with Google Authenticator

### ISSUE THREAD

**Issue by simonbutterworth** [ministryofjustice/data-platform-support#240]
### Which tool do you need help with?

User and Account

### What happened?

I moved to a new mobile phone and despite my best efforts I am no longer able to log in to AP or Github using the Google Authenticator app. I tried signing in and getting a code sent to my phone to verify me but never received one. Could someone please help? Many thanks!

**Comment by michaeljcollinsuk** [comment]
Hi @simonbutterworth I have reset your 2FA, please try to [log in to the control panel](https://controlpanel.services.analytical-platform.service.justice.gov.uk/) again and you should be prompted to set it up again.

**Comment by simonbutterworth** [comment]
Hi @michaeljcollinsuk , thanks for that - I have been able to log in to AP. Can you also reset my Github authentication (username: simonbutterworth). I tried to use the QA code on the settings (Password and Authentication) but it didn't work and I have a feeling someone had to work some magic for me there before in order for it to work?

**Comment by michaeljcollinsuk** [comment]
Glad you have been able to log in, however not sure I am following regarding your github access. What is it that you are trying to log in to that is not working, the standard github login page https://github.com/login? I am not able to reset your GitHub 2FA but [here is some guidance here that may help you](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials). However, since you are logging in to Control Panel via GitHub I would have assumed this would be working in order for you to have been able to log in to Control Panel successfully.

**Comment by simonbutterworth** [comment]
That's perfect, thank you, @michaeljcollinsuk ! I think I may have confused myself. Everything does indeed seem to be in order. I'll close the ticket. Thanks for the help!
