### ISSUE TITLE
Unable to authenticate with Google authenticator

### ISSUE THREAD

**Issue by sandygudgeon** [ministryofjustice/data-platform-support#241]
### What happened?

I haven't used the Analytical Platform for a couple of years so expected my account to be deleted or inactive.  Following steps at https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html I get as far as attempting to access the control panel, it takes to to a google authenticator 2FA page.  I have the Google app but don't have a QR code to link it to.   Can you help?

**Comment by michaeljcollinsuk** [comment]
Hi @sandygudgeon I have reset your 2FA, please try to [log in to the control panel](https://controlpanel.services.analytical-platform.service.justice.gov.uk/) again and you should be prompted to set it up again.

**Comment by sandygudgeon** [comment]
Thanks @michaeljcollinsuk I got the 2FA set up & got through that.  I now get 'Sorry, there is a problem with the service'.

**Comment by michaeljcollinsuk** [comment]
Is that an error from Control Panel? Are you able to post a screenshot please? Thanks

**Comment by sandygudgeon** [comment]
![image](https://github.com/ministryofjustice/data-platform-support/assets/15055784/6685fa94-1de5-4d8a-8d82-43843e18f326)

**Comment by michaeljcollinsuk** [comment]
@sandygudgeon I think because it had been so long since you last logged in, that your tools namespace was deleted/was not created (looking into the exact reason). In order to resolve, I have deleted your user account in the control panel, so if you go to log in again, this will recreate your user profile, which should also then trigger the creation of your tools namespace.

So please try to log in to again now (you may be prompted to setup 2FA again) and then let me know if you still encounter the error accessing the tools page. If you do get any errors, please screenshot them and add with your comment. Thanks

**Comment by sandygudgeon** [comment]
Many thanks @michaeljcollinsuk I'm in and RStudio deployed & run successfully.  I'll close this case.
