### ISSUE TITLE
Deploy Helm Chart into Cloud Platform Failed

### ISSUE THREAD

**Issue by Eve-Dolling** [ministryofjustice/data-platform-support#276]
### What happened?

I made a PR which failed at the automatic check Deploy Helm Chart into Cloud Platform. When I clicked "Details" I can see that it failed at line 356:

Error: UPGRADE FAILED: release hlt-portal-dev failed, and has been rolled back due to atomic being set: context deadline exceeded
Error: Process completed with exit code 1.
##[debug]Finishing: Upgrade the Helm chart

Can someone advise?

**Comment by Gary-H9** [comment]
Hello 👋  Usually when this happens a re-run is a good first port of call is to rerun the job, I see we both tried that on this occasion and it didn't work sadly. 

I tried increasing the timeout time to 15m minutes but I can see that hasn't worked either. 

The deployment should bring up another pod in the namespace, once thats up and stable it will remove the old pod. In this case the new pod is not starting up because of an error in the app from what I can tell.

You'll need to work to resolve this issue which I can see in the webapp container logs: 

```
{"level":"info","message":"Error in paste(\"is\", trends_CU169a$latest_month_val) : \n  object 'trends_CU169a' not found\nCalls: <Anonymous> ... gather_prison_statements -> formulate_pem_cumulative_statement -> paste\n","service":"shiny.stderr"}
│ Stream closed EOF for data-platform-app-hlt-portal-dev/data-platform-app-hlt-portal-dev-dcb9c7857-lh7xz (webapp)
```

You can look at the logs by connecting to the cloudplatform cluster and looking at the `data-platform-app-hlt-portal-dev` namespace. 

I'll leave this ticket open for now!

**Comment by Eve-Dolling** [comment]
Hi! Just checking that this update is for me? Does this mean that I need to go back and review the code? It didn't initially throw up any error but I can review again. Apologies I'm fairly new to Github.

Eve

**Comment by Gary-H9** [comment]
Hi @Eve-Dolling yeah this seems to an issue app side I'm afraid. I spoke to the team this morning and we have noticed a few other things which may be able to pinpoint the error application side. 

The [first](https://github.com/ministryofjustice/hlt-portal/pull/159/commits) commit passed but the second did not, this means that whatever changed in between these two commits has caused the issue which is stopping the container from starting. Note the ✅ and ❌ in the below image.

<img width="1423" alt="Screenshot 2023-10-13 at 09 44 29" src="https://github.com/ministryofjustice/data-platform-support/assets/26419401/2e18708f-7826-4b37-afd5-86e39550c5b0">

Here are some Kibana logs to help you troubleshoot: 

- the application [generally](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1d,to:now))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.namespace_name,negate:!f,params:(query:data-platform-app-hlt-portal-dev),type:phrase),query:(match_phrase:(kubernetes.namespace_name:data-platform-app-hlt-portal-dev))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.container_name,negate:!f,params:(query:webapp),type:phrase),query:(match_phrase:(kubernetes.container_name:webapp)))),index:'167701b0-f8c0-11ec-b95c-1d65c3682287',interval:auto,query:(language:kuery,query:'NOT%20log:%20%20%22%2Fhealthz%22'),sort:!()))
- the [error message](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/doc/167701b0-f8c0-11ec-b95c-1d65c3682287/live_kubernetes_cluster-2023.10.12?id=10a0c13b-4777-2962-c093-7cabb95c1614) (...`trends_CU169a`...)I seen in the container when I looked at the cluster

Next steps I would suggest you look at would be to:
- look into the differences between the first and second commit, focussing on that error message previously mentioned
- build the container locally to confirm you can get it up and running - if you're not comfortable doing this you can always make a change, push to github, see if the action fails, but this will be quite slow since the timeout is 15 minutes each time.

No worries at all, we are all learning!

**Comment by Eve-Dolling** [comment]
Thanks so much Gary I really appreciate the advice. At the risk of asking a stupid question, would there be any issues with me closing the pull request, going back to the local app and raising another pull request with just one commit?

Thanks,

Eve

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Gary-H9** [comment]
Hey @Eve-Dolling, if I'm following your line of thinking - it's not the number of commits that's causing you to have an issue here, it's the content of the commits to the pull request. The [first](https://github.com/ministryofjustice/hlt-portal/pull/159/commits/8e8f90276a7a6c876f204f3932e55aa6878e1521) commit has was passing but the [second](https://github.com/ministryofjustice/hlt-portal/pull/159/commits/8a6874e95cf3f3075dbaeeead1e8e2fc0c05b509) one wasn't, so my suggestion is to see what changed between the two or alternatively, start again _from_ the first successful commit. I'm sorry I can't advise as to the differences as I don't understand the application.

**Comment by Eve-Dolling** [comment]
Thanks Gary :)

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Gary-H9** [comment]
Closing as per [this](https://github.com/ministryofjustice/data-platform-support/issues/281#issue-1945912309) issue.
