### ISSUE TITLE
User Jan.Hookey@justice.gov.uk unable to access Safety diagnostic tool

### ISSUE THREAD

**Issue by NikP-B** [ministryofjustice/data-platform-support#308]
### Which tool do you need help with?

User and Account

### What happened?

User Jan Hookey unable to access **https://safety-diagnostic-tool.apps.live.cloud-platform.service.justice.gov.uk/**
EM seen by user **invalid _request (invalid user id)**
![59418ea3-dd01-42f9-a6d8-09d78d2e0036](https://github.com/ministryofjustice/data-platform-support/assets/149153741/b9b70de9-ceaf-4b82-b4ac-d79f11a2aa11)
![c9511b0b-d97a-4562-a722-dd55d96f34ad](https://github.com/ministryofjustice/data-platform-support/assets/149153741/81c3e6dd-a0a7-41a6-bbeb-a07d99e47df7)
Issue originally raised back in April under INC2022257 via MoJ service desk which never found it's way to the correct team. User states they lost access in April, then could access for a period - and now can't again.

I understand support is via GitHub tickets as I've had no reply from the user since my last contact, so raising this ticket on their behalf.

### Relevant log output

```bash
invalid _request (invalid user id)
```

**Comment by michaeljcollinsuk** [comment]
No record of a user with email Jan.Hookey@justice.gov.uk in either Control Panel users list, or Auth0. Will discuss further with the team.

**Comment by michaeljcollinsuk** [comment]
I have emailed the user to ask if this is still an issue they are facing.

**Comment by michaeljcollinsuk** [comment]
The user has emailed to confirm this is still an issue. 

@miller-william @lucypitches @lauratraceymoj as app owners for https://safety-diagnostic-tool.apps.live.cloud-platform.service.justice.gov.uk, should this user be able to access your app? I have not been able to find any record of them in Control Panel or Auth0, so from our side it looks like they have never had access. Would you be able to contact the user to check how they are attempting to access? Thanks

**Comment by lauratraceymoj** [comment]
Hi @michaeljcollinsuk we don't manage users through the control panel, instead everyone with a NOMIS account can access using their NOMIS credentials, but I suspect they're using the old link (from before we migrated to cloud platform). I'll email them from our sdt support mailbox

**Comment by michaeljcollinsuk** [comment]
@lauratraceymoj The old URL will redirect to the new cloud platform URL. Based on the screenshot provided, and as we have no record of the user of them in Auth0, it suggests they have never been able to log in - because even though auth is via NOMIS, a successful login would create a user within Auth0. So it is confusing that they mention having access and losing it. Perhaps there is an issue with the credentials they are using to authenticate with NOMIS? I have emailed them to let them know you will reach out via your support mailbox, but will leave this ticket open for further updates.
