### ISSUE TITLE
Access to IP addresses

### ISSUE THREAD

**Issue by miller-william** [ministryofjustice/data-platform-support#322]
### Which tool do you need help with?

Control Panel

### What happened?

I have an app user at an MoJ site (Worcester Probation Office) who is unable to access the `safety-diagnostic-tool` application, from the following IP address `194.33.200.10`.

From [this slack thread](https://mojdt.slack.com/archives/C032BQQHJE5/p1687422576105359?thread_ts=1687353365.670069&cid=C032BQQHJE5), it appears this could be related to MoJ -owned sub-nets.

Is it possible to add these to the options to allow access to?

**Comment by BrianEllwood** [comment]
@miller-william can you please confirm these are the ip addresses you need adding 

194.33.200.0/21
194.33.216.0/24
194.33.217.0/24
194.33.218.0/24

**Comment by miller-william** [comment]
Yes please

**Comment by BrianEllwood** [comment]
@michaeljcollinsuk @ymao2  I see that you have previously added ip addresses to the control panel is it possible to have these added too please

**Comment by michaeljcollinsuk** [comment]
@bagg3rs can I get your input on adding the above IP addresses to a new allow list?

**Comment by bagg3rs** [comment]
Please add @michaeljcollinsuk see [here](https://github.com/ministryofjustice/moj-ip-addresses/blob/29243f7ad31467a5fa936b90a873029240773963/moj-cidr-addresses.yml)

**Comment by michaeljcollinsuk** [comment]
@bagg3rs thanks, although I cant see `194.33.217.0/24` in that list, so should I leave that out?

**Comment by BrianEllwood** [comment]
Hi @miller-william I have created a new IP address list called  "Vodafone DIA Sites" please follow the following to make them available to the application.

    * Log in to control panel
    * Go to the “Manage app” page for your app
    * Under deployment settings for Dev/Prod, find the IP_RANGES setting and click the Edit button
    * Check the box for the newly added IP allowlist
    * Click the Update IP Allowlists button

* The changes made will only be applied on the next deployment of the app, so please redeploy your application in order to make the IP's available.
* To redeploy, the app owner can either re-run a recent workflow build, or push a commit and create a PR to trigger a dev deploy. Merging the PR to the main branch will deploy to production. Further information about deploying can be found in the [user guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/apps/rshiny-app.html#apps-hosted-on-cloud-platform).
*
Please let me know how it goes

Cheers

Brian
