### ISSUE TITLE
Deployment to production: test is failing

### ISSUE THREAD

**Issue by andriasarri** [ministryofjustice/data-platform-support#352]
### What happened?

https://github.com/ministryofjustice/hlt-portal/actions/runs/6948161288/job/18903523574?pr=218

**Comment by ymao2** [comment]
The PR raised in this issue was my attempt to solve issue 😊 
The original issue is below 
https://github.com/ministryofjustice/hlt-portal/actions/runs/6948063017/job/18903216169

I spent time for checking,  the main reason is that somehow the following package
`python-pip-whl`  cannot be found from https://mirror.bytemark.co.uk/ubuntu/pool/universe/p/python-pip,   it tries to fetch `python-pip-whl_20.0.2-5ubuntu1.10_all.deb` , which doesn't exist,    

The older successful jobs was looking for `python-pip-whl_20.0.2-5ubuntu1.9_all.deb`  which exists in that website
Not sure such minor ubuntu from `1.9` to `1.10` is due to the `apt-get update`?  should we add extra mirror website to look for this new version? 

also I noticed  the jobs for refreshing base rshiny image failed last week, maybe due to same reason?

https://github.com/ministryofjustice/analytics-platform-rshiny/actions/runs/6910444181/job/18803590353

**Comment by ymao2** [comment]
@andriasarri,   I just tried hour ago,   the website [https://mirror.bytemark.co.uk](https://mirror.bytemark.co.uk/ubuntu/pool/universe/p/python-pip) finally provides those missing files!, now the errors 404 have gone,  I had similar experiences for other apps,   but normally those missing links will be resumed very quickly, not like this one. 

I just re-triggered your https://github.com/ministryofjustice/hlt-portal/pull/217,  now it has been deployed into dev env successfully , I will close my own PR

**Comment by ymao2** [comment]
Confirmed by the user,  now the app has been deployed successfully on prod env
