### ISSUE TITLE
Can't add user to a bucket

### ISSUE THREAD

**Issue by RichardBright** [ministryofjustice/data-platform-support#77]
### Which tool do you need help with?

S3

### What happened?

I'm attempting to grant a user (urbankucharcik) access to my bucket (alpha-hmpps-staticdatatables) but he does not appear in the drop-down list of users when I type in his name.

**Comment by LouiseABowler** [comment]
Hi @RichardBright, I can't see @urbankucharcik in our user list at the moment. You'll only be able to add them once they have set up their Analytical Platform account. I can see that they're in the `moj-analytical-services` organisation already so that's the first step done; once they've logged into [Control Panel](https://controlpanel.services.analytical-platform.service.justice.gov.uk/) for the first time that will finish off their account setup and you should be able to add them to the bucket after that.

**Comment by RichardBright** [comment]
Thanks @LouiseABowler this has now resolved the issue.
